// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: pkg/api/proto/edge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EdgeTestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestVal       string                 `protobuf:"bytes,1,opt,name=testVal,proto3" json:"testVal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeTestReq) Reset() {
	*x = EdgeTestReq{}
	mi := &file_pkg_api_proto_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeTestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeTestReq) ProtoMessage() {}

func (x *EdgeTestReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeTestReq.ProtoReflect.Descriptor instead.
func (*EdgeTestReq) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_edge_proto_rawDescGZIP(), []int{0}
}

func (x *EdgeTestReq) GetTestVal() string {
	if x != nil {
		return x.TestVal
	}
	return ""
}

type EdgeTestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestVal       string                 `protobuf:"bytes,1,opt,name=testVal,proto3" json:"testVal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeTestResp) Reset() {
	*x = EdgeTestResp{}
	mi := &file_pkg_api_proto_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeTestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeTestResp) ProtoMessage() {}

func (x *EdgeTestResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeTestResp.ProtoReflect.Descriptor instead.
func (*EdgeTestResp) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_edge_proto_rawDescGZIP(), []int{1}
}

func (x *EdgeTestResp) GetTestVal() string {
	if x != nil {
		return x.TestVal
	}
	return ""
}

var File_pkg_api_proto_edge_proto protoreflect.FileDescriptor

var file_pkg_api_proto_edge_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x65, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x27, 0x0a, 0x0b, 0x45, 0x64, 0x67, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x22, 0x28, 0x0a, 0x0c, 0x45, 0x64,
	0x67, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65,
	0x73, 0x74, 0x56, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x73,
	0x74, 0x56, 0x61, 0x6c, 0x32, 0x39, 0x0a, 0x04, 0x45, 0x64, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x04,
	0x54, 0x65, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x64, 0x67,
	0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x45, 0x64, 0x67, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42,
	0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x79,
	0x6c, 0x6f, 0x52, 0x69, 0x6c, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x69, 0x6f, 0x73, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_pkg_api_proto_edge_proto_rawDescOnce sync.Once
	file_pkg_api_proto_edge_proto_rawDescData []byte
)

func file_pkg_api_proto_edge_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_edge_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_edge_proto_rawDesc), len(file_pkg_api_proto_edge_proto_rawDesc)))
	})
	return file_pkg_api_proto_edge_proto_rawDescData
}

var file_pkg_api_proto_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_proto_edge_proto_goTypes = []any{
	(*EdgeTestReq)(nil),  // 0: proto.EdgeTestReq
	(*EdgeTestResp)(nil), // 1: proto.EdgeTestResp
}
var file_pkg_api_proto_edge_proto_depIdxs = []int32{
	0, // 0: proto.Edge.Test:input_type -> proto.EdgeTestReq
	1, // 1: proto.Edge.Test:output_type -> proto.EdgeTestResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_edge_proto_init() }
func file_pkg_api_proto_edge_proto_init() {
	if File_pkg_api_proto_edge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_edge_proto_rawDesc), len(file_pkg_api_proto_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_edge_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_edge_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_edge_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_edge_proto = out.File
	file_pkg_api_proto_edge_proto_goTypes = nil
	file_pkg_api_proto_edge_proto_depIdxs = nil
}
