// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/api/proto/leader.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Leader_Test_FullMethodName = "/proto.Leader/Test"
)

// LeaderClient is the client API for Leader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeaderClient interface {
	Test(ctx context.Context, in *LeaderTestReq, opts ...grpc.CallOption) (*LeaderTestResp, error)
}

type leaderClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaderClient(cc grpc.ClientConnInterface) LeaderClient {
	return &leaderClient{cc}
}

func (c *leaderClient) Test(ctx context.Context, in *LeaderTestReq, opts ...grpc.CallOption) (*LeaderTestResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaderTestResp)
	err := c.cc.Invoke(ctx, Leader_Test_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaderServer is the server API for Leader service.
// All implementations must embed UnimplementedLeaderServer
// for forward compatibility.
type LeaderServer interface {
	Test(context.Context, *LeaderTestReq) (*LeaderTestResp, error)
	mustEmbedUnimplementedLeaderServer()
}

// UnimplementedLeaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaderServer struct{}

func (UnimplementedLeaderServer) Test(context.Context, *LeaderTestReq) (*LeaderTestResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedLeaderServer) mustEmbedUnimplementedLeaderServer() {}
func (UnimplementedLeaderServer) testEmbeddedByValue()                {}

// UnsafeLeaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaderServer will
// result in compilation errors.
type UnsafeLeaderServer interface {
	mustEmbedUnimplementedLeaderServer()
}

func RegisterLeaderServer(s grpc.ServiceRegistrar, srv LeaderServer) {
	// If the following call pancis, it indicates UnimplementedLeaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Leader_ServiceDesc, srv)
}

func _Leader_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderTestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Leader_Test_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderServer).Test(ctx, req.(*LeaderTestReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Leader_ServiceDesc is the grpc.ServiceDesc for Leader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Leader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Leader",
	HandlerType: (*LeaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _Leader_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/proto/leader.proto",
}
