// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: pkg/api/proto/leader.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaderTestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestVal       string                 `protobuf:"bytes,1,opt,name=testVal,proto3" json:"testVal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderTestReq) Reset() {
	*x = LeaderTestReq{}
	mi := &file_pkg_api_proto_leader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderTestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderTestReq) ProtoMessage() {}

func (x *LeaderTestReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_leader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderTestReq.ProtoReflect.Descriptor instead.
func (*LeaderTestReq) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_leader_proto_rawDescGZIP(), []int{0}
}

func (x *LeaderTestReq) GetTestVal() string {
	if x != nil {
		return x.TestVal
	}
	return ""
}

type LeaderTestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestVal       string                 `protobuf:"bytes,1,opt,name=testVal,proto3" json:"testVal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderTestResp) Reset() {
	*x = LeaderTestResp{}
	mi := &file_pkg_api_proto_leader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderTestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderTestResp) ProtoMessage() {}

func (x *LeaderTestResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_leader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderTestResp.ProtoReflect.Descriptor instead.
func (*LeaderTestResp) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_leader_proto_rawDescGZIP(), []int{1}
}

func (x *LeaderTestResp) GetTestVal() string {
	if x != nil {
		return x.TestVal
	}
	return ""
}

var File_pkg_api_proto_leader_proto protoreflect.FileDescriptor

var file_pkg_api_proto_leader_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0d, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x22, 0x2a,
	0x0a, 0x0e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x32, 0x3f, 0x0a, 0x06, 0x4c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x54, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x79, 0x6c, 0x6f, 0x52, 0x69,
	0x6c, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x69, 0x6f, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_api_proto_leader_proto_rawDescOnce sync.Once
	file_pkg_api_proto_leader_proto_rawDescData []byte
)

func file_pkg_api_proto_leader_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_leader_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_leader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_leader_proto_rawDesc), len(file_pkg_api_proto_leader_proto_rawDesc)))
	})
	return file_pkg_api_proto_leader_proto_rawDescData
}

var file_pkg_api_proto_leader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_proto_leader_proto_goTypes = []any{
	(*LeaderTestReq)(nil),  // 0: proto.LeaderTestReq
	(*LeaderTestResp)(nil), // 1: proto.LeaderTestResp
}
var file_pkg_api_proto_leader_proto_depIdxs = []int32{
	0, // 0: proto.Leader.Test:input_type -> proto.LeaderTestReq
	1, // 1: proto.Leader.Test:output_type -> proto.LeaderTestResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_leader_proto_init() }
func file_pkg_api_proto_leader_proto_init() {
	if File_pkg_api_proto_leader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_leader_proto_rawDesc), len(file_pkg_api_proto_leader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_leader_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_leader_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_leader_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_leader_proto = out.File
	file_pkg_api_proto_leader_proto_goTypes = nil
	file_pkg_api_proto_leader_proto_depIdxs = nil
}
